### ISSUE TITLE
Error when using plugin 

### ISSUE THREAD

**Issue by wheelerlaw** [heptio/vscode-jsonnet#58]
Can't really figure out what is going on. 
Compiled the go version of jsonnet, set `jsonnet.executablePath` to point to the compiled binary. 
But I keep getting the following errors:

```
[Error - 9:06:02 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: ENOENT: no such file or directory, stat 'c:\c%3A\openshift_templates\src\main\resources\templates\v2\dc.jsonnet'
  Code: -32603 
```

**Comment by wheelerlaw** [comment]
Another error:
```
{ Error: ENOENT: no such file or directory, stat 'c:\c%3A\openshift_templates\src\main\resources\templates\v2\dc.jsonnet'
    at fs.statSync (fs.js:973:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
    at VsDocumentManager.get (C:\Users\wlaw\.vscode\extensions\heptio.jsonnet-0.1.0\out\server\local.js:25:32)
    at Analyzer.onHover (C:\Users\wlaw\.vscode\extensions\heptio.jsonnet-0.1.0\out\compiler\static-analysis\analyzer.js:41:103)
    at connection.onHover.position (C:\Users\wlaw\.vscode\extensions\heptio.jsonnet-0.1.0\out\server\server.js:80:21)
    at handleRequest (C:\Users\wlaw\.vscode\extensions\heptio.jsonnet-0.1.0\node_modules\vscode-jsonrpc\lib\main.js:361:27)
    at processMessageQueue (C:\Users\wlaw\.vscode\extensions\heptio.jsonnet-0.1.0\node_modules\vscode-jsonrpc\lib\main.js:252:17)
    at Immediate.<anonymous> (C:\Users\wlaw\.vscode\extensions\heptio.jsonnet-0.1.0\node_modules\vscode-jsonrpc\lib\main.js:242:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'c:\\c%3A\\openshift_templates\\src\\main\\resources\\templates\\v2\\dc.jsonnet' }
```

**Comment by bryanl** [comment]
I'm going to try to reproduce your issues in Windows.

**Comment by wheelerlaw** [comment]
@bryanl Any luck?
